version: '3.4'

services:
  buildingbuddydemo:
    image: buildingbuddydemo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
